[build]
builder = "nixpacks"
command = "dotnet publish -c Release -r linux-x64 -o out"
buildCommand = "echo building! GiovannyRailWay"

[env]
DOTNET_VERSION = "8.0"
ASPNETCORE_ENVIRONMENT = "Production"
PORT = "8080"

